export type PreviewExercise={id:number;name:string;equipment:string;pattern:string;difficulty:string;cues:string[];regression?:string;progression?:string;videoState:'queued'|'published';videoUrl?:string};

export const previewExercises:PreviewExercise[]=[
{id:21,name:'Bodyweight Squat',equipment:'Bodyweight',pattern:'Squat',difficulty:'Beginner',cues:['Brace your core','Sit between the hips','Keep knees tracking over toes'],regression:'Box Squat',progression:'Goblet Squat',videoState:'queued'},
{id:25,name:'Reverse Lunge',equipment:'Bodyweight',pattern:'Lunge',difficulty:'Beginner',cues:['Step back under control','Keep front foot planted','Drive through the front leg'],regression:'Supported Split Squat',progression:'Dumbbell Reverse Lunge',videoState:'queued'},
{id:34,name:'Glute Bridge',equipment:'Bodyweight / Mat',pattern:'Hinge',difficulty:'Beginner',cues:['Ribs down','Squeeze glutes at the top','Avoid arching the low back'],regression:'Short-range Glute Bridge',progression:'Single-leg Glute Bridge',videoState:'queued'},
{id:45,name:'Push-Up',equipment:'Bodyweight',pattern:'Push',difficulty:'Beginner-Intermediate',cues:['Keep body in one line','Lower with control','Press the floor away'],regression:'Incline Push-Up',progression:'Decline Push-Up',videoState:'queued'},
{id:55,name:'Forearm Plank',equipment:'Bodyweight / Mat',pattern:'Core',difficulty:'Beginner',cues:['Brace the trunk','Keep hips level','Breathe without losing position'],regression:'Plank from knees',progression:'Long-lever Plank',videoState:'queued'},
{id:59,name:'Dead Bug',equipment:'Bodyweight / Mat',pattern:'Core',difficulty:'Beginner',cues:['Keep ribs down','Move slowly','Maintain low-back control'],regression:'Heel Tap',progression:'Loaded Dead Bug',videoState:'queued'},
{id:70,name:'Mountain Climber',equipment:'Bodyweight',pattern:'Cardio / Core',difficulty:'Beginner-Intermediate',cues:['Hands under shoulders','Drive knees smoothly','Keep hips steady'],regression:'Slow Mountain Climber',progression:'Fast Mountain Climber',videoState:'queued'},
{id:79,name:'Dumbbell Goblet Squat',equipment:'Dumbbell',pattern:'Squat',difficulty:'Beginner',cues:['Hold weight close','Brace before descending','Stand tall through the floor'],regression:'Bodyweight Squat',progression:'Double-Dumbbell Front Squat',videoState:'queued'},
{id:89,name:'Dumbbell Romanian Deadlift',equipment:'Dumbbells',pattern:'Hinge',difficulty:'Beginner-Intermediate',cues:['Push hips back','Keep weights close','Stop before the back rounds'],regression:'Bodyweight Good Morning',progression:'Single-leg Dumbbell RDL',videoState:'queued'},
{id:96,name:'Dumbbell Bench Press',equipment:'Dumbbells + Bench',pattern:'Push',difficulty:'Beginner',cues:['Set shoulder blades','Lower under control','Press smoothly'],regression:'Dumbbell Floor Press',progression:'Incline Dumbbell Press',videoState:'queued'},
{id:105,name:'One-arm Dumbbell Row',equipment:'Dumbbell + Bench',pattern:'Pull',difficulty:'Beginner',cues:['Keep torso stable','Pull elbow toward hip','Control the lowering phase'],regression:'Chest-supported Dumbbell Row',progression:'Heavier Dumbbell Row',videoState:'queued'},
{id:133,name:'Kettlebell Goblet Squat',equipment:'Kettlebell',pattern:'Squat',difficulty:'Beginner',cues:['Keep bell close','Brace the trunk','Stand through the whole foot'],regression:'Bodyweight Squat',progression:'Double-Kettlebell Front Squat',videoState:'queued'},
{id:157,name:'Cable Chest Press',equipment:'Cable',pattern:'Push',difficulty:'Beginner',cues:['Set stance','Keep ribs controlled','Press without shrugging'],regression:'Band Chest Press',progression:'Single-arm Cable Press',videoState:'queued'},
{id:160,name:'Cable Lat Pulldown',equipment:'Cable / Pulldown',pattern:'Pull',difficulty:'Beginner',cues:['Set shoulders down','Pull elbows toward ribs','Avoid leaning far back'],regression:'Band Lat Pulldown',progression:'Pull-Up',videoState:'queued'},
{id:179,name:'Leg Press',equipment:'Leg Press Machine',pattern:'Squat',difficulty:'Beginner',cues:['Keep feet planted','Control the depth','Do not lock knees aggressively'],regression:'Bodyweight Box Squat',progression:'Hack Squat',videoState:'queued'},
{id:208,name:'Inverted Row',equipment:'Bar / Smith Machine',pattern:'Pull',difficulty:'Beginner-Intermediate',cues:['Keep body straight','Pull chest toward bar','Control the descent'],regression:'More upright Inverted Row',progression:'Feet-elevated Inverted Row',videoState:'queued'},
{id:218,name:'Band Row',equipment:'Resistance Band',pattern:'Pull',difficulty:'Beginner',cues:['Anchor securely','Keep shoulders down','Pause at the finish'],regression:'Lighter Band Row',progression:'Heavier Band Row',videoState:'queued'},
{id:235,name:'Farmer Carry',equipment:'Dumbbells / Kettlebells',pattern:'Carry',difficulty:'Beginner',cues:['Stand tall','Walk with control','Keep shoulders level'],regression:'Lighter Farmer Carry',progression:'Heavier or Longer Carry',videoState:'queued'},
{id:254,name:'Treadmill Walk',equipment:'Treadmill',pattern:'Cardio',difficulty:'Beginner',cues:['Use a natural stride','Stay tall','Choose a sustainable pace'],regression:'Overground Walk',progression:'Incline Treadmill Walk',videoState:'queued'},
{id:260,name:'Rowing Machine',equipment:'Rowing Machine',pattern:'Cardio',difficulty:'Beginner-Intermediate',cues:['Drive with legs first','Keep handle path smooth','Recover under control'],regression:'Easy Rowing Intervals',progression:'Longer or Faster Intervals',videoState:'queued'},
{id:264,name:'Standing Quad Stretch',equipment:'None',pattern:'Mobility',difficulty:'Beginner',cues:['Stand tall','Keep knees near each other','Use gentle tension'],regression:'Supported Quad Stretch',progression:'Longer Controlled Hold',videoState:'queued'}
];

export const previewById=new Map(previewExercises.map(x=>[x.id,x]));
